require('dotenv').config();
const { generateEntitySecretCiphertext } = require('@circle-fin/developer-controlled-wallets');
const crypto = require('crypto');

const LATCH_CIRCLE_URL = process.env.LATCH_CIRCLE_URL;
const LATCH_CIRCLE_TOKEN = process.env.LATCH_CIRCLE_TOKEN;

// Sends a USDC transfer request THROUGH Latch's policy proxy for Circle,
// instead of calling Circle directly with the Circle SDK.
// The entitySecretCiphertext is still generated by us (as Circle requires),
// but the actual transfer request is routed through Latch for policy enforcement.
async function latchCreateTransaction({ walletId, tokenId, destinationAddress, amount }) {
  const entitySecretCiphertext = await generateEntitySecretCiphertext({
    apiKey: process.env.CIRCLE_API_KEY,
    entitySecret: process.env.CIRCLE_ENTITY_SECRET,
  });

  const body = {
    idempotencyKey: crypto.randomUUID(),
    entitySecretCiphertext,
    walletId,
    tokenId,
    destinationAddress,
    amounts: [String(amount)],
    feeLevel: 'MEDIUM',
  };

  const url = `${LATCH_CIRCLE_URL}/proxy/v1/w3s/developer/transactions/transfer`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${LATCH_CIRCLE_TOKEN}`,
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Latch Circle proxy error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  return data;
}

module.exports = { latchCreateTransaction };
